language: node_js
node_js:
- 12.4.0
cache:
  directories:
  - node_modules
dist: trusty
install:
- npm install
script:
- npm run test
- npm run build:lib
notifications:
  email:
  - ebrehault@gmail.com
before_deploy:
  if [[ $TRAVIS_TAG ]]; then
    cd dist/ngx-state-traverser;
  else
    git config --global user.email "build@travis-ci.com" &&
    git config --global user.name "Travis CI" &&
    export PACKAGE_VERSION=$(npm run get_version | tail -n 1) &&
    echo "TAGGING $PACKAGE_VERSION..." &&
    git tag $PACKAGE_VERSION;
  fi
deploy:
  - provider: releases
    api_key:
      secure: VHdKG1tNq/4K5HGp0mPSYAU6TQfJLlpIwwn/H4YfdUl1sdP4dFNTj1UikQ9WOKRO5VEBuEOiqrwKEnddHt6Yr/mGPjC4uv89uUd50SNilnB0nj8FE5Dp4xA+OZ39PN8pmVDesAaPm7kWE8H0GRUdu43wb22brwYie54z0vvCCdUq0EysGI3Z8A/tGoPLbYScmmr7lz/hHvXnQYBcB0/ZUOZMP8vAbsszqbIurD2UVR+cfRw8FLZHdllP5XEKTNY+FSM5/0lclg75yN840MyHmrDpHYktOq2iufepq78EA+v5ZxS8hmyWtJW8SnBOJ9BBT6xfNsgpTh5jTfahyIH1lYRVXLyIYGFk7g1uUvt0uZkvTYAdhmv+Z4XiTnlY3mp3xSfv6rT0xZUntd9r6HgV+oEen68MCGV1GulnTZZ8a4GhNmrJ3nA3B6PWqU1nut3yi3QlsIsNocKIHtJDkoafgly6idN1Nvdcjw7k22otImqv250uT+v8z7o8x+DdgiDT8VlGjHjH1aa1zAJ1Ha9cJf/ROfP2dd7GyhrAAXWuhwBNpAYAQlBpSXNmCsTHWsjq2IG4Vuw5+oeAsmZEGnUrrwhJCPmjCOblK2VaeSqiPiJOFFUw1gK0lDBmlmiRRNBu+Do3w2q4yGVhHuBixWcLncGhuwDKzP2PNvLEQoN4HdI=
    name: Build $PACKAGE_VERSION
    on:
      repo: guillotinaweb/ngx-state-traverser
      branch: master
  - provider: npm
    email: ebrehault@gmail.com
    skip_cleanup: true
    api_key:
      secure: l2sP0IMo6k9zoJf6Fy5U81V2DG3xC2HgZZ+iv8fb1fBRrrdkFwxrpMpoe8+UsULKko1fgnPoW0xLK6oMtOnBITKSw4EWXDbykKg6fW282JXCoatDb5FVXelqyK1XzX+f/lLbhrOFDdH23Di9Ra4xiDLVjwnrcqzulQy1XevfPoYJZ8OOtFJ+dfNc/n8eXhWElyjjCPNL5MZ4WxL/9s+j0b3/Ls8dNe7A0vUxQEZiYn72HmcmE+ChOuiQelkyqNRYuX1JzH4L47INrm40bER6p5BeCwRWzKCG29z65p5TXZrsHqxM4VbaK501iZgofmxR7eirQWb5WFa9Bhrk0wPMZnyT59LszE0OW+GQAQpeeExYXMUxLG4JwZg/h9JPVy6sdJTmh6CDE1ksD++nFk8RyIrt8dMLr0cXRr1mKu2Eq2y0Ck/FP61d3aSuEXbqXRmpYAi6ISHpCdaURBfzypZy2Z2riLPPFfE3Le0UfvjwDgyuXoqZO0xGVFyf4oIu+Xhh1PAYteKH0517ydxhXJxxviXwMEccC2Vtv/OB/vZuDmde/O6eDwZLPXg+hofIjo/mwHZRai28hYXE+IVA6d99Y9PblKE6VI23O+6tiKJJFefzREGUN4OhUTzXDuiymM+FNXBUoriIOzIQMnPy4rUls6yHBBbR3L/DXC8BvkQXKO0=
    on:
      tags: true
      repo: guillotinaweb/ngx-state-traverser
      branch: master
